### ISSUE TITLE
Workflow task fails with new Sandbox (initial build required)

### ISSUE THREAD

**Issue by nsaunders** [calgaryscientific/veracode-gradle-plugin#45]
I added project properties, as shown, in gradle.properties:
```
app_id=******
sandbox_id=******
build_version=0.0.0-0-SNAPSHOT
```

Then, I added the dependencies to my classpath:
```
buildscript {
  dependencies {
    classpath 'com.veracode.vosp.api.wrappers:vosp-api-wrappers-java:17.11.4.9'
    classpath 'gradle.plugin.com.calgaryscientific.gradle:veracodePlugin:0.4.0'
  }
}
```
(Side note: Is it better to use Maven Central rather than manually downloading the Veracode jar?)

Then, I applied the plugin:
```
apply plugin: 'com.calgaryscientific.gradle.veracode'
```

Finally, I tried to execute the Sandbox Workflow task:
```
macdaddy123:phatproject nsaunders$ ./gradlew veracodeSandboxWorkflow
:veracodeSandboxWorkflow FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':veracodeSandboxWorkflow'.
> ERROR: Could not find a build for application=****** and sandbox=******
  See /Users/nsaunders/Projects/hg/projects/41st/phatproject/build/veracode/buildinfo-******-******-latest.xml for details!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.764 secs
macdaddy123:phatproject nsaunders$ 
```

buildinfo-******-******-latest.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<error>Could not find a build for application=****** and sandbox=******</error>
```

What  am I missing here?

It seems to me that a workflow task should take care of all of the details of creating/updating/deleting a build as needed, uploading artifacts, and triggering a scan. Is this assumption incorrect? 

Your help and insight would be greatly appreciated. Thanks in advance!

**Comment by nsaunders** [comment]
I did miss one part of build.gradle:

```
veracodeSetup {
  id = project.findProperty('veracodeId')
  key = project.findProperty('veracodeSecret')
  sandboxFilesToUpload = fileTree(dir: 'build/libs/', include: "phatproject-all-${version}.jar").getFiles()
}
```

**Comment by DavidGamba** [comment]
Hi @therealnicksaunders,

Veracode announced the Maven integration in November and I haven't had the time to update the project yet. But yes, I totally agree it is the way to go.

As far as your error in particular, you aren't doing anything wrong. The problem is that there is no single existing build in your sandbox and the tool fails in that case, if you manually create a build you should be good to go afterwards.

Check `veracodeSandboxCreateBuild`.

The worflow task depends on the previous build status to decide what to do next:
https://github.com/calgaryscientific/veracode-gradle-plugin/blob/master/src/main/groovy/com/calgaryscientific/gradle/VeracodeWorkflow.groovy#L102

But I haven't added the case where there is no existing build in place, which is where you are at with a new sandbox.

Once you have the first build you should be good to go...

Finally, if you want to give it a go feel free to submit a PR with the change, otherwise I'll take me a couple of weeks before I get to work on the Veracode tooling again. Hope that the workaround of creating a build is enough for you until then.

**Comment by DavidGamba** [comment]
Published https://github.com/calgaryscientific/veracode-gradle-plugin/releases/tag/v0.5.0 which addresses this issue.
